# Homework 1

## Q1. Pandas version

In [5]:
pd.__version__

'3.0.5'

## Getting the data

In [37]:
import pandas as pd

In [38]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [39]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

## Q2. Records count

In [40]:
df.shape

(10000, 11)

## Q3. Fuel types

In [11]:
df['fuel_type'].nunique()

3

## Q4. Missing values

In [12]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

## Q5. Max fuel efficiency

In [13]:
df['fuel_efficiency_mpg'].max()

np.float64(41.2)

## Q6. Median value of horsepower

1. Find the median value of the `horsepower` column in the dataset.

In [14]:
df['horsepower'].median()

np.float64(254.0)

In [43]:
df.describe().round(3)

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.000,10000.000,10000.000,10000.000,9123.000,10000.000,9736.000,10000.000
mean,1999.550,3.504,2268.807,6.035,254.446,4286.754,18.888,29.998
std,14.208,0.952,183.447,0.543,22.845,266.212,1.280,2.930
min,1975.000,2.000,1590.000,4.000,171.000,3320.000,14.000,19.800
25%,1987.000,3.000,2150.000,6.000,239.000,4110.000,18.000,28.000
50%,2000.000,4.000,2270.000,6.000,254.000,4280.000,18.900,30.000
75%,2012.000,4.000,2390.000,6.000,270.000,4470.000,19.700,31.900
max,2024.000,5.000,3110.000,8.000,334.000,5460.000,23.800,41.200

2. Next, calculate the most frequent value of the same `horsepower` column.

In [44]:
most_frequent_hp = df['horsepower'].mode()[0]

In [45]:
most_frequent_hp

np.float64(252.0)

3. Use the `fillna` method to fill the missing values in the `horsepower` column with the most frequent value from the previous step.

In [46]:
df['horsepower'] = df['horsepower'].fillna(most_frequent_hp)

In [47]:
df['horsepower'].isnull().sum()

np.int64(0)

4. Now, calculate the median value of `horsepower` once again.

In [48]:
df['horsepower'].median()

np.float64(252.0)

## Q7. Sum of weights

1. Select all the cars from Asia

In [50]:
asia_cars = df[df['origin'] == 'Asia']

In [52]:
asia_cars

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,252.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4
...,...,...,...,...,...,...,...,...,...,...,...
9984,2011,Asia,Gasoline,Front-wheel drive,3,2410,6,256.0,4610,20.2,32.4
9987,2004,Asia,Diesel,All-wheel drive,3,2180,6,266.0,4530,18.6,29.0
9990,1975,Asia,Diesel,Front-wheel drive,4,1940,6,236.0,3630,19.7,32.4
9994,1993,Asia,Gasoline,Rear-wheel drive,2,2360,6,257.0,4610,22.2,30.1
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0

2. Select only columns `vehicle_weight` and `model_year`

In [53]:
asia_cars_subset = asia_cars[['vehicle_weight', 'model_year']]

In [54]:
asia_cars_subset

      vehicle_weight  model_year
2               4240        1996
6               4310        1992
8               4230        1997
10              4420        1978
15              3950        2007
...              ...         ...
9984            4610        2011
9987            4530        2004
9990            3630        1975
9994            4610        1993
9996            4370        1993

[2994 rows x 2 columns]

3. Select the first 7 values

In [55]:
asia_cars_first_7 = asia_cars_subset.head(7)
asia_cars_first_7

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

4. Get the underlying NumPy array. Let's call it `X`.

In [56]:
import numpy as np

In [59]:
X = asia_cars_first_7.values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

5. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.

In [62]:
XTX = X.T.dot(X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

6. Invert `XTX`.

In [64]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

7. Create an array `y` with values `[1100, 1300, 800, 900, 1000, 1100, 1200]`.

In [65]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

8. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.

In [67]:
w = XTX_inv.dot(X.T).dot(y)
w

array([0.13644777, 0.2327492 ])

9. What's the sum of all the elements of the result?

In [68]:
ans = w.sum()

In [74]:
print("Sum of all elements:", ans.round(3))

Sum of all elements: 0.369