## Homework 6

### Dataset

The goal of this homework is to create a regression model for predicting the car fuel efficiency (column `'fuel_efficiency_mpg'`).

In [1]:
# %pip install pandas numpy seaborn matplotlib scikit-learn

In [2]:
import pandas as pd
import numpy as np

import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline

In [3]:
data = 'https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv'

In [4]:
!wget $data -O homework-week-6.csv

--2026-10-22 08:17:50--  https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 635180 (620K) [text/plain]
Saving to: ‘homework-week-6.csv’

homework-week-6.csv 100%[===================>] 620.29K  --.-KB/s    in 0.01s

2026-10-22 08:17:50 (48.9 MB/s) - ‘homework-week-6.csv’ saved [635180/635180]

In [5]:
df = pd.read_csv('homework-week-6.csv')

In [6]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

### Preparing the dataset 

Preparation:

* Fill missing values with zeros.
* Do the split with these exact calls:

In [7]:
df.dtypes

model_year               int64
origin                     str
fuel_type                  str
drivetrain                 str
num_doors                int64
engine_displacement      int64
num_cylinders            int64
horsepower             float64
vehicle_weight           int64
acceleration           float64
fuel_efficiency_mpg    float64
dtype: object

In [8]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [9]:
df.horsepower = df.horsepower.fillna(0)

In [10]:
df.acceleration = df.acceleration.fillna(0)

In [11]:
from sklearn.model_selection import train_test_split

df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=1)

In [12]:
len(df_train), len(df_val), len(df_test), len(df)

(6000, 2000, 2000, 10000)

In [13]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [14]:
y_train = df_train.fuel_efficiency_mpg.values
y_val = df_val.fuel_efficiency_mpg.values
y_test = df_test.fuel_efficiency_mpg.values

In [15]:
del df_train['fuel_efficiency_mpg']
del df_val['fuel_efficiency_mpg']
del df_test['fuel_efficiency_mpg']

In [16]:
df_train

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration
0,2011,USA,Gasoline,Front-wheel drive,4,2370,6,284.0,4280,19.0
1,2012,USA,Diesel,All-wheel drive,3,2460,6,288.0,4580,18.8
2,1985,Europe,Gasoline,All-wheel drive,3,2070,6,230.0,4150,20.6
3,2005,Europe,Diesel,Front-wheel drive,5,2050,5,249.0,4120,0.0
4,2004,Asia,Gasoline,Front-wheel drive,2,2160,6,241.0,4020,17.9
...,...,...,...,...,...,...,...,...,...,...
5995,1988,Asia,Gasoline,Rear-wheel drive,2,2290,6,235.0,4110,17.9
5996,2009,Asia,Gasoline,Rear-wheel drive,3,2400,6,245.0,4460,17.5
5997,2012,Asia,Gasoline,Front-wheel drive,3,2510,6,271.0,4440,19.1
5998,2003,Europe,Gasoline,All-wheel drive,4,1900,5,211.0,4000,19.4
5999,1989,Europe,Gasoline,Front-wheel drive,4,2370,6,273.0,4270,17.8

## Question 1

Let's train a decision tree regressor to predict the `fuel_efficiency_mpg` variable. 

* Train a model with `max_depth=1`.


Which original feature is used for splitting the data? If you use
`DictVectorizer`, map a one-hot feature such as `origin=USA` back to its
original column name.


* `'vehicle_weight'`
* `'model_year'`
* `'origin'`
* `'fuel_type'`

In [17]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.feature_extraction import DictVectorizer

In [18]:
train_dicts = df_train.to_dict(orient='records')

In [19]:
dv = DictVectorizer(sparse=False)
X_train = dv.fit_transform(train_dicts)

In [20]:
val_dicts = df_val.to_dict(orient='records')
X_val = dv.transform(val_dicts)

In [21]:
feature_names = dv.get_feature_names_out()

In [22]:
dt = DecisionTreeRegressor(max_depth=1)
dt.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=1)

In [23]:
# Find the feature index used by the root split
# Map that index to the encoded feature name

split_index = dt.tree_.feature[0]
split_feature = feature_names[split_index]

print("Split index:", split_index)
print("Encoded split feature:", split_feature)
print("Original feature:", split_feature.split("=")[0])

Split index: 9
Encoded split feature: model_year
Original feature: model_year

## Question 2

Train a random forest regressor with these parameters:

* `n_estimators=10`
* `random_state=1`
* `n_jobs=-1` (optional - to make training faster)


What's the RMSE of this model on the validation data?

* 0.1837
* 1.837
* 18.37
* 183.7

In [24]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

In [25]:
rf = RandomForestRegressor(
    n_estimators=10,
    random_state=1,
    n_jobs=-1,
)

rf.fit(X_train, y_train)

RandomForestRegressor(n_estimators=10, n_jobs=-1, random_state=1)

In [26]:
y_pred = rf.predict(X_val)
rmse = np.sqrt(mean_squared_error(y_val, y_pred))
rmse.round(3)      # Answer: 1.834

np.float64(1.834)

## Question 3

Now let's experiment with the `n_estimators` parameter

* Try these values of this parameter: `[10, 50, 100, 150]`.
* Set `random_state` to `1`.
* Evaluate the model on the validation dataset.


Which value gives the lowest validation RMSE? Consider 3 decimal places for
calculating the answer.

- 10
- 50
- 100
- 150

In [27]:
scores = []

n_estimators = [10, 50, 100, 150]

for n_estimator in n_estimators:
    rf = RandomForestRegressor(n_estimators=n_estimator, random_state=1, n_jobs=-1,)
    rf.fit(X_train, y_train)

    y_pred = rf.predict(X_val)
    rmse = np.sqrt(mean_squared_error(y_val, y_pred))

    scores.append((n_estimator, rmse))

In [28]:
columns = ['n_estimators', 'rmse']
df_scores = pd.DataFrame(scores, columns=columns)

In [29]:
df_scores.sort_values("rmse").round(3)  # Answer: n_estimators = 100

   n_estimators   rmse
2           100  1.768
3           150  1.768
1            50  1.770
0            10  1.834

## Question 4

Let's select the best `max_depth`:

* Try different values of `max_depth`: `[10, 15, 20, 25]`
* For each of these values,
  * try different values of `n_estimators` from `[10, 50, 100, 150]`
  * calculate the mean RMSE 
* Fix the random seed: `random_state=1`


What's the best `max_depth`, using the mean RMSE?

* 10
* 15
* 20
* 25

In [30]:
scores = []

for d in [10, 15, 20, 25]:
    for n_estimator in [10, 50, 100, 150]:
        rf = RandomForestRegressor(
            n_estimators=n_estimator,
            max_depth=d,
            random_state=1,
            n_jobs=-1,
        )

        rf.fit(X_train, y_train)
        y_pred = rf.predict(X_val)
        rmse = np.sqrt(mean_squared_error(y_val, y_pred))

        scores.append((d, n_estimator, rmse))

In [31]:
columns = ['max_depth','n_estimators', 'rmse']
df_scores = pd.DataFrame(scores, columns=columns)

In [32]:
mean_scores = (
    df_scores.groupby("max_depth")["rmse"]
    .mean()
    .sort_values()
)

print(mean_scores.round(4))
print("Best max_depth:", mean_scores.idxmin())

max_depth
10    1.7569
20    1.7827
15    1.7848
25    1.7874
Name: rmse, dtype: float64
Best max_depth: 10

# Question 5

We can extract feature importance information from tree-based models. 

At each step of the decision tree learning algorithm, it finds the best split. 
When doing it, we can calculate "gain" - the reduction in impurity before and after the split. 
This gain is quite useful in understanding what are the important features for tree-based models.

In Scikit-Learn, tree-based models contain this information in the
[`feature_importances_`](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestRegressor.html#sklearn.ensemble.RandomForestRegressor.feature_importances_)
field. 

For this homework question, we'll find the most important feature:

* Train the model with these parameters:
  * `n_estimators=10`,
  * `max_depth=20`,
  * `random_state=1`,
  * `n_jobs=-1` (optional)
* Get the feature importance information from this model


What's the most important feature (among these 4)? 

* `vehicle_weight`
*	`horsepower`
* `acceleration`
* `engine_displacement`

In [33]:
rf_importance = RandomForestRegressor(
            n_estimators=10,
            max_depth=20,
            random_state=1,
            n_jobs=-1,
        )

rf_importance.fit(X_train, y_train)

RandomForestRegressor(max_depth=20, n_estimators=10, n_jobs=-1, random_state=1)

In [34]:
feature_names = dv.get_feature_names_out()
importance = rf_importance.feature_importances_

In [35]:
df_importance = pd.DataFrame({
    "feature": feature_names,
    "importance": importance,
})

In [36]:
df_importance.sort_values("importance", ascending=False)   # Answer: vehicle_weight

                         feature  importance
9                     model_year    0.295822
15                vehicle_weight    0.203649
6             fuel_type=Gasoline    0.160713
8                     horsepower    0.078254
4            engine_displacement    0.061008
0                   acceleration    0.055466
14                    origin=USA    0.042232
5               fuel_type=Diesel    0.021128
2   drivetrain=Front-wheel drive    0.020005
11                     num_doors    0.019724
7               fuel_type=Hybrid    0.011685
1     drivetrain=All-wheel drive    0.007873
10                 num_cylinders    0.006939
12                   origin=Asia    0.006479
3    drivetrain=Rear-wheel drive    0.005636
13                 origin=Europe    0.003389

## Question 6

Now let's train an XGBoost model! For this question, we'll tune the `eta` parameter:

* Install XGBoost
* Create DMatrix for train and validation
* Create a watchlist
* Train a model with these parameters for 100 rounds:

```
xgb_params = {
    'eta': 0.3, 
    'max_depth': 6,
    'min_child_weight': 1,
    
    'objective': 'reg:squarederror',
    'nthread': 8,
    
    'seed': 1,
    'verbosity': 1,
}
```

Now change `eta` from `0.3` to `0.1`.

Which eta leads to the best RMSE score on the validation dataset?

* 0.3
* 0.1
* Both give equal value

In [37]:
%pip install xgboost

Requirement already satisfied: xgboost in /usr/local/python/3.14.2/lib/python3.14/site-packages (3.4.1)
Requirement already satisfied: numpy in /usr/local/python/3.14.2/lib/python3.14/site-packages (from xgboost) (2.5.4)
Requirement already satisfied: scipy in /usr/local/python/3.14.2/lib/python3.14/site-packages (from xgboost) (1.18.1)
Requirement already satisfied: nvidia-nccl-cu13 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from xgboost) (2.32.3)

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [38]:
import xgboost as xgb

In [39]:
features = list(dv.get_feature_names_out())
dtrain = xgb.DMatrix(X_train, label=y_train, feature_names=features)
dval = xgb.DMatrix(X_val, label=y_val, feature_names=features)

In [40]:
watchlist = [(dtrain, 'train'), (dval, 'val')]

In [41]:
scores = {}

In [42]:
%%capture output

xgb_params = {
    'eta': 0.3, 
    'max_depth': 6,
    'min_child_weight': 1,
    
    'objective': 'reg:squarederror',
    'nthread': 8,
    
    'seed': 1,
    'verbosity': 1,               
}

model = xgb.train(xgb_params, dtrain, num_boost_round=100,
                  evals=watchlist, 
                  verbose_eval=5)

In [43]:
def parse_xgb_output(output):
    results = []

    for line in output.stdout.strip().split('\n'):
        it_line, train_line, val_line = line.split('\t')

        it = int(it_line.strip('[]'))
        train = float(train_line.split(':')[1])
        val = float(val_line.split(':')[1])

        results.append((it, train, val))
    
    columns = ['num_iter', 'train_rmse', 'val_rmse']
    df_results = pd.DataFrame(results, columns=columns)
    return df_results

In [44]:
df_scores = parse_xgb_output(output)
df_scores

    num_iter  train_rmse  val_rmse
0          0     2.40653   2.46782
1          5     1.59328   1.76216
2         10     1.47125   1.73205
3         15     1.41908   1.73512
4         20     1.39368   1.73766
5         25     1.35837   1.74359
6         30     1.33243   1.74548
7         35     1.29290   1.75198
8         40     1.25326   1.76296
9         45     1.21527   1.77244
10        50     1.18645   1.77517
11        55     1.14797   1.78668
12        60     1.10265   1.79401
13        65     1.06590   1.80143
14        70     1.04604   1.80444
15        75     1.02727   1.80682
16        80     0.99487   1.81308
17        85     0.96970   1.81600
18        90     0.94986   1.82135
19        95     0.91805   1.82544
20        99     0.90106   1.82646

In [45]:
key = 'eta=%s' % (xgb_params['eta'])
scores[key] = parse_xgb_output(output)
key

'eta=0.3'

In [46]:
%%capture output

xgb_params = {
    'eta': 0.1, 
    'max_depth': 6,
    'min_child_weight': 1,
    
    'objective': 'reg:squarederror',
    'nthread': 8,
    
    'seed': 1,
    'verbosity': 1,               
}

model = xgb.train(xgb_params, dtrain, num_boost_round=100,
                  evals=watchlist, 
                  verbose_eval=5)

In [47]:
df_scores = parse_xgb_output(output)
df_scores

    num_iter  train_rmse  val_rmse
0          0     2.74739   2.78635
1          5     2.12109   2.20428
2         10     1.80592   1.93152
3         15     1.64286   1.80346
4         20     1.55847   1.75076
5         25     1.50918   1.72751
6         30     1.47544   1.71667
7         35     1.44978   1.71287
8         40     1.43074   1.71289
9         45     1.41543   1.71310
10        50     1.40368   1.71358
11        55     1.39009   1.71570
12        60     1.37884   1.71688
13        65     1.37172   1.71812
14        70     1.36283   1.71919
15        75     1.35099   1.72057
16        80     1.34578   1.72100
17        85     1.33480   1.72192
18        90     1.32546   1.72303
19        95     1.32292   1.72324
20        99     1.31192   1.72481

In [48]:
key = 'eta=%s' % (xgb_params['eta'])
scores[key] = parse_xgb_output(output)
key

'eta=0.1'

In [49]:
scores.keys()

dict_keys(['eta=0.3', 'eta=0.1'])

In [51]:
for key, df_score in scores.items():
    best_idx = df_score["val_rmse"].idxmin()
    best_row = df_score.loc[best_idx]

    print(
        f"{key}: "
        f"RMSE={best_row['val_rmse']:.5f}, "
        f"iteration={int(best_row['num_iter'])}"
    )         # Answer: eta=0.1

eta=0.3: RMSE=1.73205, iteration=10
eta=0.1: RMSE=1.71287, iteration=35